# Generated by Django 3.0.6 on 2020-06-29 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Elije una foto', null=True, upload_to='')),
                ('profesion', models.CharField(blank=True, help_text='Profesión', max_length=30, null=True)),
                ('presentacion', models.TextField(blank=True, help_text='Acerca de ti', max_length=200, null=True)),
                ('enlace_referencias', models.CharField(blank=True, help_text='Link', max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(help_text='Ingrese el nombre del proyecto', max_length=25, verbose_name='Nombre')),
                ('descripcion_proyecto', models.TextField(help_text='Acerca del Proyecto', max_length=200)),
                ('foto_proyecto', models.ImageField(blank=True, help_text='Elije una foto', null=True, upload_to='')),
                ('foto_proyecto2', models.ImageField(blank=True, help_text='Elije una foto', null=True, upload_to='')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, help_text='Fecha de publicacion')),
                ('rubro', models.CharField(choices=[('AO', 'Administración/Oficina'), ('AL', 'Almacén'), ('AC', 'Atención a clientes'), ('CT', 'CallCenter/Telemercadeo'), ('CE', 'Comercio Exterior'), ('CP', 'Compras'), ('CC', 'Comunicación'), ('CO', 'Construccion y obra'), ('CF', 'Contabilidad/Finanzas'), ('DG', 'Dirección/Gerencia'), ('DA', 'Diseño/Artes gráficas'), ('DC', 'Docencia'), ('HO', 'Hostelería'), ('IN', 'Informática'), ('IG', 'Ingeniería'), ('IC', 'Investigación y Calidad'), ('LA', 'Legal, Asesoría'), ('LO', 'Logística'), ('MR', 'Mantenimiento y Reparaciones Técnicas'), ('MF', 'Manufactura'), ('MS', 'Medicina/Salud'), ('MT', 'Mercadotécnia'), ('OP', 'Operarios'), ('PR', 'Producción'), ('PU', 'Publicidad'), ('RH', 'Recursos Humanos'), ('SG', 'Servicios Generales'), ('SE', 'Seguridad'), ('TC', 'Telecomunicaciones'), ('TR', 'Transporte'), ('TU', 'Turismo'), ('VE', 'Ventas'), ('OT', 'Otros')], help_text='Seleccione el rubro', max_length=25)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Usuario')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
