# Generated by Django 3.0.6 on 2020-06-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_ususario',
            new_name='nombre_usuario',
        ),
    ]
