# Generated by Django 3.0.6 on 2020-06-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200615_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(help_text='Ingrese el nombre del proyecto', max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(help_text='Ingrese su nombre', max_length=25, verbose_name='Nombre'),
        ),
    ]
