# Generated by Django 3.0.6 on 2020-06-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200616_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_publicacion']},
        ),
    ]
