# Generated by Django 3.0.6 on 2020-06-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200618_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='rubro',
            field=models.CharField(choices=[('AO', 'Administración/Oficina'), ('AL', 'Almacén'), ('AC', 'Atención a clientes'), ('CT', 'CallCenter/Telemercadeo'), ('CE', 'Comercio Exterior'), ('CP', 'Compras'), ('CC', 'Comunicación'), ('CO', 'Construccion y obra'), ('CF', 'Contabilidad/Finanzas'), ('DG', 'Dirección/Gerencia'), ('DA', 'Diseño/Artes gráficas'), ('DC', 'Docencia'), ('HO', 'Hostelería'), ('IN', 'Informática'), ('IG', 'Ingeniería'), ('IC', 'Investigación y Calidad'), ('LA', 'Legal, Asesoría'), ('LO', 'Logística'), ('MR', 'Mantenimiento y Reparaciones Técnicas'), ('MF', 'Manufactura'), ('MS', 'Medicina/Salud'), ('MT', 'Mercadotécnia'), ('OP', 'Operarios'), ('PR', 'Producción'), ('PU', 'Publicidad'), ('RH', 'Recursos Humanos'), ('SG', 'Servicios Generales'), ('SE', 'Seguridad'), ('TC', 'Telecomunicaciones'), ('TR', 'Transporte'), ('TU', 'Turismo'), ('VE', 'Ventas'), ('OT', 'Otros')], help_text='Seleccione el rubro', max_length=25),
        ),
    ]
