# Generated by Django 3.0.6 on 2020-06-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200623_1932'),
        ('Home', '0004_auto_20200622_2137'),
    ]

    operations = [
    ]
