# Generated by Django 3.0.6 on 2020-06-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200624_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='User',
        ),
    ]
