# Generated by Django 3.0.6 on 2020-06-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200624_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='User',
            new_name='user',
        ),
    ]
