# Generated by Django 3.0.6 on 2020-06-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20200625_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='usermod',
        ),
    ]
