# Generated by Django 3.0.6 on 2020-06-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200625_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usermod',
            new_name='user',
        ),
    ]
