# Generated by Django 3.0.6 on 2020-06-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20200625_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='userr',
        ),
    ]
